const data = {
    status: "success",
    items: [
      {
        id: 1,
        title: "Jabon en Polvo Roma",
        price: 34.90,
        image: require('./img/product01.jpg'),
        category: "detergentes",
        cantidad: 1,
      },
      {
        id: 2,
        title: "Multilimpiador desinfectante Pinol",
        price: 42.50,
        image: require('./img/product02.jpg'),
        category: "detergentes",
        cantidad: 1,
      },
      {
        id: 3,
        title: "Cafe soluble Great Value colombiano",
        price: 95.00,
        image: require('./img/product03.jpg'),
        category: "abarrotes",
        cantidad: 1,
      },
      {
        id: 4,
        title: "Papel higienico Elite",
        price: 59.00,
        image: require('./img/product04.jpg'),
        category: "limpieza",
        cantidad: 1,
      },
      {
        id: 5,
        title: "Atún Dolores aleta amarilla",
        price: 36.90,
        image: require('./img/product05.jpg'),
        category: "abarrotes",
        cantidad: 1,
      },
      {
        id: 6,
        title: "Pan tostado Bimbo fibra",
        price: 24.50,
        image: require('./img/product06.jpg'),
        category: "abarrotes",
        cantidad: 1,
      },
      {
        id: 7,
        title: "Cereal kellogg's Corn Flakes",
        price: 44.40,
        image: require('./img/product07.jpg'),
        category: "abarrotes",
        cantidad: 1,
      },
      {
        id: 8,
        title: "Azucar morena Zulka",
        price: 58.00,
        image: require('./img/product08.jpg'),
        category: "abarrotes",
        cantidad: 1,
      },
      {
        id: 9,
        title: "Aceite puro de soya Nutrioli",
        price: 38.90,
        image: require('./img/product09.jpg'),
        category: "abarrotes",
        cantidad: 1,
      },
      {
        id: 10,
        title: "Arroz verde Valle",
        price: 31.00,
        image: require('./img/product10.jpg'),
        category: "abarrotes",
        cantidad: 1,
      },
      {
        id: 11,
        title: "Rajas de jalapeño La Costeña",
        price: 19.70,
        image: require('./img/product11.jpg'),
        category: "abarrotes",
        cantidad: 1,
      },
      {
        id: 12,
        title: "Mayonesa McCormick",
        price: 54.00,
        image: require('./img/product12.jpg'),
        category: "abarrotes",
        cantidad: 1,
      }
    ],
  };
  
  export default data;